version: "3.9"
services:
  airline-api:
    build: .
    restart: always
    ports:
     - 8081:8081
    environment:
      eureka.client.service-url.defaultZone: http://airline:8761/eureka

networks:
  default:
    name: discovery-server_default
